name: tests

on:
  push:

jobs:
  unit-test:
    runs-on: node:19
    permissions:
      contents: read
    strategy:
      matrix:
        include:
        - TEST_PATH: ./test/unit/fasset/library
        - TEST_PATH: ./test/unit/fasset/mock
        - TEST_PATH: ./test/unit/bots
        - TEST_PATH: ./test/unit/governance
        - TEST_PATH: ./test/unit/utils
        - TEST_PATH: ./test/unit/fasset/implementation
        - TEST_ARG: test/unit/gasReport/GasReport.ts
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run test
      run: yarn hardhat test --network hardhat ${{ matrix.TEST_ARG }}
      env:
        TEST_PATH: ${{ matrix.TEST_PATH }}


  test-contract-integration:
    runs-on: node:19
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn test_integration_hh


  test-linter:
    runs-on: node:19
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run lint


  test-slither-test:
    runs-on: node:19
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install slither-analyzer
      run: apt update -y && apt install -y python3-pip && pip3 install slither-analyzer
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run slither


  test-coverage:
    runs-on: node:19
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run cov


  test-fuzzer:
    runs-on: node:19
    permissions:
      contents: read
    env:
      NODE_OPTIONS: "--max_old_space_size=6144"
      LOOPS: 5000
      CHANGE_PRICE_AT: '300,600,...'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run fuzzing_fasset
    - name: Archive fuzzer log
      uses: actions/upload-artifact@v3
      with:
        name: fuzzer-log
        path: test_logs/fasset-fuzzing.log
